name: Test
on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"

    name: Test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install pre-commit

      - name: Print pre-commit version
        run: pre-commit --version

      - name: Run pre-commit install
        run: pre-commit install

      - name: Run pre-commit try-repo
        run: pre-commit try-repo . --verbose --all-files
